version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=techie-rajesh_spring_boot

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
